spring:
  application:
    name: server-turbine
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  # 配置spring boot actuator端口
  port: 18031
