server:
  port: 18082
spring:
  application:
    name: service-review
#####################################################################################################
# mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: '032052'
  jpa:
    hibernate:
      #ddl-auto:设为create表示每次都重新建表
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
  thymeleaf:
    cache: false
#####################################################################################################
# Eureka服务器配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#####################################################################################################
# 打印日志
logging:
  level:
    root: INFO
    org.springframework.cloud.netflix.feign: INFO
#####################################################################################################
## INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
