server:
  port: 18040
spring:
  application:
    name: server-gateway
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://45.40.240.250:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: '032052'
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      stat-view-servlet:
        login-username: admin
        login-password: admin
      max-wait: 1000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  jpa:
    hibernate:
      #ddl-auto:设为create表示每次都重新建表
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
zuul:
  #全部服务忽略敏感头(全部服务都可以传递cookie)
  sensitive-headers:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 30000
    connect-timeout-millis: 50000
##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 64000
ribbon:
  ReadTimeout: 64000
  ConnectTimeout: 64000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true
management:
  security:
    enabled: false